name: zen
favicon: null
layout_spectrum: 0.01740362076088786
typography_spectrum: 0.8509741649031639
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9471407996024936
  lightness: 0.9572788819205016
  saturation: 0.9358547108713537
  rhythmicContrast: 0.6758422302082181
purpose: []
